FROM ubuntu:21.10


#https://gnu-linux.org/installation-of-ns3-on-ubuntu.html
#RUN apt-get update && \
#    apt-get install -y gcc g++ python python-dev qt4-dev-tools mercurial cmake 
    #libc6-dev libc6-dev-i386 
    #g++-multilib 
    #gdb valgrind gsl-bin libgsl0-dev 
    #libgsl0ldbl flex bison libfl-dev tcpdump sqlite sqlite3 libsqlite3-dev libxml2 libxml2-dev libgtk2.0-0 libgtk2.0-dev vtun lxc uncrustify doxygen graphviz imagemagick texlive texlive-extra-utils texlive-latex-extra texlive-font-utils dvipng python-sphinx dia python-pygraphviz python-kiwi python-pygoocanvas libgoocanvas-dev libboost-signals-dev libboost-filesystem-dev openmpi-bin openmpi-common openmpi-doc libopenmpi-dev

VOLUME [ "/ns3" ]